version: "{branch}.build.{build}"
skip_tags: true

branches:
  only:
    - master

clone_folder:  c:\projects\apcu

install:
  ps: .appveyor\install.ps1

cache:
  c:\build-cache -> appveyor.yml, .appveyor\install.ps1

environment:
  BIN_SDK_VER: 2.1.2
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: x64
      VC: vc15
      PHP_VER: 7.2
      TS: 0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: x64
      VC: vc15
      PHP_VER: 7.2
      TS: 1
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: x86
      VC: vc15
      PHP_VER: 7.2
      TS: 0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: x86
      VC: vc15
      PHP_VER: 7.2
      TS: 1
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: x64
      VC: vc15
      PHP_VER: 7.3
      TS: 0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: x64
      VC: vc15
      PHP_VER: 7.3
      TS: 1
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: x86
      VC: vc15
      PHP_VER: 7.3
      TS: 0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: x86
      VC: vc15
      PHP_VER: 7.3
      TS: 1
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: x64
      VC: vc15
      PHP_VER: 7.4
      TS: 0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: x64
      VC: vc15
      PHP_VER: 7.4
      TS: 1
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: x86
      VC: vc15
      PHP_VER: 7.4
      TS: 0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: x86
      VC: vc15
      PHP_VER: 7.4
      TS: 1

build_script:
  ps: .appveyor\build.ps1

after_build:
  ps: .appveyor\package.ps1

test_script:
  ps: .appveyor\test.ps1
